name: splat-env
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - defaults
  - git
  - pytorch
  - torchvision
  - pytorch-cuda=11.8       # Comment this out if you're on Mac
  - pytorch3d
  - pip:
      - numpy
      - opencv-python
      - imageio
      - scikit-image
      - matplotlib
      - tqdm
      - einops
      - transformers
      - timm
      - xatlas                # Optional; skip if it fails
      - OpenEXR
      - Imath
      - opencv
      - python=3.10
      - pytorch
      - torchvision
      - torchaudio
      - pytorch-cuda=11.8
      - opencv
      - openexr
      - huggingface_hub

